# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:
  - linux
  - osx
r:
  - oldrel
  - devel
matrix:
  include:
    - r: release
      os: linux
      after_success:
       - Rscript -e 'devtools::install_github("r-lib/pkgdown")'
       - Rscript -e 'pkgdown::build_site()'
       - Rscript -e 'covr::codecov()'
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_PAT
        on:
          branch: devel
        local_dir: ${TRAVIS_BUILD_DIR}/docs
        target_branch: preview
    - r: release
      os: osx
  exclude:
    - r: devel
      os: osx